---
title: "concretecuring"
author: "Ewout Knoester"
date: "2023-06-09"
output: html_document
---

# Set R and packages
```{r setup}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks

library(dplyr) # Data cleaning
library(emmeans) # Post hoc
library(ggplot2) # Plots
library(ggpubr) # Asterisks for significance levels
library(ggthemes) # Plot layout
library(multcomp) # Post hoc significance letters
library(NCmisc) # Check packages used
library(nlme) # Model lme
library(readxl) # Load excel
library(rstatix) # Stats anova
library(stringr) # Find strings
library(writexl) # Save excel

# Function to facilitate averaging dataset
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(sum = sum(x[[col]]),
      mean = base::mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]])))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- plyr::rename(data_sum, c("mean" = varname))
 return(data_sum)
}

```


#  Data prep
<!--
 Data info:
  All 678 pics from the Cement curing 2021 experiment
  6 treatments x 5 species x 10 replicates x 2 time points (start & end), 22 missing end pics
  Pictures cropped so Soft substrate (Sand, Rubble, Seagrass) is omitted as much as possible:
  Focus on benthic species on discs
  For each pic, 50 random points from Coralnet, all AI ID confirmed by Anniek Vos
  -->
```{r data prep}

# Data import
data0.raw <- read_excel("Raw data/cementcuring2021coralnet.xlsx")
data1.clean <- dplyr::select(data0.raw, c("Name", "Date", "Patch", "Treatment", "Structure", "Label"))
names(data1.clean) <- c("Pic.ID", "Date", "Species", "Curingtime", "Replicate", "Label")

# Inspect which categories are common
data1.clean.totals <- data1.clean %>%
  group_by(Label) %>%
  tally()
data1.clean.totals <- data1.clean.totals[order(data1.clean.totals$n, decreasing = T),]

# Get full names and functional groups from labelset Coralnet
labelset <- read_excel("Raw data/Labelset_manual.xlsx")

# Specify functional groups further
labelset$FG[labelset$FG == 'Other Invertebrates'] <- 'Other'
labelset$FG[labelset$FG == 'Hard Substrate'] <- 'Hard substrate'
labelset$FG[labelset$FG == 'Soft Substrate'] <- 'Soft substrate'
labelset$FG[labelset$Label == 'SC'] <- 'Soft coral'
labelset$FG[labelset$Label == 'Tubmus'] <- 'Soft coral'
labelset$FG[labelset$Label == 'Xendae'] <- 'Soft coral'
labelset$FG[labelset$Label == 'Rhy'] <- 'Soft coral'
labelset$FG[labelset$Label == 'Mil'] <- 'Hard coral'
labelset$FG[labelset$FG == 'Algae'] <- 'Macroalgae'
labelset$FG[labelset$Label == 'TA'] <- 'Turf algae'
labelset$FG[labelset$FG == 'CCA'] <- 'Hard substrate'

# Merge to combine info
data1.clean <- left_join(data1.clean, labelset, by = "Label")
data1.clean <- dplyr::select(data1.clean, -c("Label"))

# Correct input error
data1.clean$Name[data1.clean$Name == 'Porites (massive)'] <- 'Porites (branching)'

# Leave out Seagrass and Sand: only focus on benthos on disks
data1.clean <- subset(data1.clean, Name != "Sand")
data1.clean <- subset(data1.clean, Name != "Seagrass")
data1.clean <- subset(data1.clean, Name != "Framer")

# Export clean data
write_xlsx(data1.clean, "Cement_curing_clean_data.xlsx")

```

# Data cleaning
```{r data cleaning}

# Load clean data
data2.selex <- read_excel("Cement_curing_clean_data.xlsx")

# Set order of factors (for graphs later)
data2.selex$Replicate <- as.factor(data2.selex$Replicate)
## Species
data2.selex$Species <- as.factor(data2.selex$Species)
levels(data2.selex$Species) <- c("Acropora formosa", "Acropora verweyi", "Millepora tenera", "Pocillopora verrucosa", "Porites cylindrica")
## Curingtime
data2.selex$Curingtime <- as.factor(data2.selex$Curingtime)
levels(data2.selex$Curingtime) <- c("1 Day", "1 Month", "1 Week", "2 Months", "2 Weeks", "3 Days", "4 Months")
data2.selex$Curingtime <- factor(data2.selex$Curingtime,  levels=c("1 Day", "3 Days", "1 Week", "2 Weeks", "1 Month", "2 Months", "4 Months"))
## Functional groups
data2.selex$FG <- factor(data2.selex$FG,  levels=c("Hard substrate", "Other", "Turf algae", "Macroalgae", "Soft coral", "Hard coral"))

# Simplify ID
data2.selex$Pic.ID <- paste(data2.selex$Date, data2.selex$Species, data2.selex$Curingtime, data2.selex$Replicate, sep = ".")

# Get Total counts (between 28 - 50) per survey (not always 50 because sand, seagrass and frame points removed)
data2.counts <- data2.selex %>%
  group_by(Pic.ID) %>%
  tally()
data2.counts <- as.data.frame(data2.counts)

# Get counts per Functional group
data3.ARC <- data2.selex %>%
  group_by(Date, Species, Curingtime, Replicate, FG, .drop = F) %>%
  tally()
data3.ARC$Pic.ID <- paste(data3.ARC$Date, data3.ARC$Species, data3.ARC$Curingtime, data3.ARC$Replicate, sep = ".")
data3.ARC <- as.data.frame(data3.ARC)

# Get cover by dividing Functional group counts/ Total counts
data3.ARC <- left_join(data3.ARC, data2.counts, by = "Pic.ID") # Combine data frames
data3.ARC <- data3.ARC[!is.na(data3.ARC$n.y),] # Remove disks without end pic/data
data3.ARC$Cover <- data3.ARC$n.x / data3.ARC$n.y * 100 

# Clean data
data3.ARC$Date <- format(data3.ARC$Date, "%m/%Y")
data3.ARC <- dplyr::select(data3.ARC, -c("n.x", "n.y", "Pic.ID"))

```

# Analysis
```{r analysis}

# THREE-WAY REPEATED MEASURES
datareal <- subset(data3.ARC, FG == "Hard coral")
datareal$Frag.ID <- as.factor(paste(datareal$Species, datareal$Curingtime, datareal$Replicate, sep = "."))
datareal$Date <- as.factor(str_sub(as.character(datareal$Date), start = -4))

# Summarize data
datareal.mean <- datareal %>%
  group_by(Species, Curingtime, Date) %>%
  get_summary_stats(Cover, type = "mean_ci")

# Model
lme.3W <- lme(sqrt(Cover) ~ Curingtime*Species*Date, random = ~1|Frag.ID,  data = datareal,
              weights = varIdent(form = ~1 | Date*Species))

# Model validation
mod <- lme.3W # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
base::plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
base::plot(datareal$Curingtime, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
base::plot(datareal$Species, resid(mod, type = "pearson")) # residuals split over Treatment
abline(0,0)
base::plot(datareal$Date, resid(mod, type = "pearson")) # residuals split over Treatment
abline(0,0)
base::plot(fitted(mod) ~ datareal$Cover) # response data vs fitted
par(op)

# Model output
car::Anova(lme.3W)

# Post hoc
hsd <- emmeans(lme.3W, specs = pairwise ~ Date |Species, adjust = "tukey", type = "response")
hsd$contrasts

hsd.all <- emmeans(lme.3W, specs = pairwise ~ Date |Species*Curingtime, adjust = "tukey", type = "response")
# hsd.all$contrasts

```

# Plotting
```{r plotting}

# OVERALL PLOT
## Get average start value of coral cover per species
data4.start <- subset(data3.ARC, Date == "06/2021" & FG == "Hard coral")
data4.start <- data_summary(data4.start, varname = "Cover", groupnames = c("Species"))
data4.start <- dplyr::select(data4.start, c("Species", "Cover"))

## Get main data ready
data4.plot <- subset(data3.ARC, Date == "06/2022")
data4.plot <- data_summary(data4.plot, varname = "Cover", groupnames = c("Species", "Curingtime", "FG"))
data4.plot$CI.low <- data4.plot$Cover - (data4.plot$se * qnorm(0.975))
data4.plot$CI.high <- data4.plot$Cover + (data4.plot$se * qnorm(0.975))

## Labels
labs <- c("A. cf. muricata", "A. verweyi", "M. tenera", "P. verrucosa", "P. cylindrica")
names(labs) <- c("Acropora formosa", "Acropora verweyi", "Millepora tenera", "Pocillopora verrucosa", "Porites cylindrica")

## Plot
ggplot(data4.plot, aes(fill = FG, y = Cover, x = Curingtime)) + 
  geom_hline(data = data4.start, aes(yintercept = Cover), colour = "#A05800", size = 0.8)+  
  facet_wrap(~Species, nrow = 5, strip.position = "right", labeller = labeller(Species = labs))+
    geom_bar(position = "stack", stat = "identity", width = 0.8)+
    scale_fill_manual(values = c("#bfbfbf", "#FFCAFB", "#A3FF9A", "#53AB4A", "#FDF294", "#ffb55a"))+
    labs(y = "Cover (%)", x = "Curing time", fill = "Category")+
    scale_y_continuous(expand = c(0,0), limits = c(0, 110),
                       breaks = c(0, 25, 50, 75, 100), labels = c("0", "", "50", "", "100"))+
    geom_bar(data = data4.plot[(data4.plot$FG == "Hard coral"),], stat = "identity", 
             aes(x = Curingtime, y = Cover), alpha=0, size=1, color="black", width = 0.8)+
    geom_errorbar(data = data4.plot[(data4.plot$FG == "Hard coral"),],
                  aes(x = Curingtime, ymin = CI.low, ymax = CI.high), width = 0.1, size = 0.6)+
    theme_economist()+
    theme(
      axis.title.x = element_text(color = "black", vjust = -1, size = 13),
      axis.text.x=element_text(size = 11, face = "bold", vjust = 3),
      axis.title.y = element_text(color = "black" , vjust=4, size = 13),
      axis.text.y=element_text(size = 11, face = "bold", vjust = 0.5, hjust = 1, margin=margin(r=0)),
      legend.text=element_text(size=11),
      legend.title= element_blank(),
      strip.text = element_text(size = 13, face = "italic", vjust = 1.2),
      plot.margin = unit(c(0, 0.1, 0.5, 0.5), "cm"),
      panel.background = element_rect(fill = "#FCFCFC"),
      plot.background = element_rect(fill = "#FFFFFF"),
      panel.grid.major = element_line(colour = "#797979", size = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      legend.position = "top",
      panel.spacing = unit(1, "lines")
      )
ggsave("Concretecuring_Overall.tiff", width = 18, height = 22, units = "cm", dpi=1200, compression = "lzw")

# SPECIES X DATE PLOT
## Data prep
data3.ARC.HC <- subset(data3.ARC, FG == "Hard coral")
data4.plotSxD <- data_summary(data3.ARC.HC, varname = "Cover", groupnames = c("Date", "Species"))

# Determine height of significance signs
## Get end values
data4.end <- subset(data3.ARC, Date == "06/2022" & FG == "Hard coral")
data4.end <- data_summary(data4.end, varname = "Cover", groupnames = c("Species"))
data4.end <- dplyr::select(data4.end, c("Species", "Cover"))
## Merge with start values and select highest
data4.all <- left_join(data4.start, data4.end, by = "Species")
data4.all$Cover.high <- ifelse(data4.all$Cover.x < data4.all$Cover.y, data4.all$Cover.y, data4.all$Cover.x)
data4.all$Cover.high <- data4.all$Cover.high + 2 # Add some margin

# Labs
labslong <- c("Acropora cf. muricata", "Acropora verweyi", "Millepora tenera", "Pocillopora verrucosa", "Porites cylindrica")

# Plot
ggplot(data4.plotSxD, aes(fill = Date, y = Cover, x = Species)) + 
    geom_bar(stat = "identity", position = position_dodge())+
    scale_fill_manual(values = c("#A05800", "#ffb55a"))+
    labs(y = "Hard coral cover (%)", x = "Species", fill = "Date")+
    scale_y_continuous(expand = c(0,0), limits = c(0, 47))+
    scale_x_discrete(labels=labslong)+
    geom_errorbar(data = data4.plotSxD, aes(x = Species, ymin = Cover - se, ymax = Cover + se), 
                  width = 0.1, size = 0.6, position = position_dodge(.9))+
    theme_economist()+
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(size = 12, face = "italic", angle = -35,  hjust=0.1, vjust = -0.2),
      axis.title.y = element_text(color = "black" , vjust=4, size = 13),
      axis.text.y=element_text(size = 11, face = "bold", vjust = 0.5, hjust = 1, margin=margin(r=0)),
      legend.text=element_text(size=12, face = "bold"),
      legend.position = c(0.90, 0.80),
      plot.margin = unit(c(0, 1, 0.5, 0.5), "cm"),
      panel.background = element_rect(fill = "#FCFCFC"),
      plot.background = element_rect(fill = "#FFFFFF"),
      panel.grid.major = element_line(colour = "#797979", size = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      panel.spacing = unit(1, "lines")
      )+
   stat_compare_means(data = data3.ARC.HC, label =  "p.signif", label.y = data4.all$Cover.high,
                      size = 9, aes(group = Date), method = "anova")
ggsave("Concretecuring_SxD.tiff", width = 18, height = 12, units = "cm", dpi=1200, compression = "lzw")

```
# Check packages used
```{r}

knitr::purl("concretecuring.Rmd")
list.functions.in.file("concretecuring.R")
unlink("concretecuring.R")

```

